- project: new
  arguments:
    project_name: test_project_1
    project_type: ANDROID
- action: set_project_framework
  arguments:
    framework_name: Mozilla test
- action: upload_file
  arguments:
    test_filename: /Users/egao/Downloads/dummy-test.zip
    data_filename: /Users/egao/Downloads/files.zip
    application_filename: /Users/egao/Downloads/ignore.apk
- action: set_project_parameters
  arguments:
    parameters: [
        {
            key: TASKCLUSTER_CLIENT_ID,
            value: project/autophone/bitbar-x-perf-g5
        },
        {
            key: TASKCLUSTER_ACCESS_TOKEN,
            value: hidden_random_value
        },
        {
            key: TC_WORKER_TYPE,
            value: gecko-t-ap-perf-g5
        },
        {
            key: TC_WORKER_CONF,
            value: gecko-t-ap
        }
    ]
    force_overwrite: False
- action: set_device_group
  arguments:
    device_group_name: Edwin_Test
- action: start_test_run
  arguments:
    name: overall_test_1
- action: notify_test_run_complete
  arguments:
    interval: 2
    timeout: 120